version: 2

before:
  hooks:
    - git tag cli/{{ .Tag }}
    - git push origin cli/{{ .Tag }}

builds:
  - id: server
    main: ./cmd
    binary: lunar
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

  - id: cli
    dir: cli
    main: .
    binary: lunar-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: server-archive
    ids:
      - server
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

  - id: cli-archive
    ids:
      - cli
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}-cli_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

dockers_v2:
  - images:
      - "dimiro1/lunar"
    tags:
      - "v{{ .Version }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
    dockerfile: goreleaser.Dockerfile

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
