// Code generated by tools/gen; DO NOT EDIT.

package cmd

import (
	"fmt"

	"github.com/dimiro1/lunar/cli/client"
	"github.com/spf13/cobra"
)

var _ = fmt.Sprintf // suppress unused import

var executionsCmd = &cobra.Command{
	Use:   "executions",
	Short: "Function execution history and logs",
}

func init() {
	rootCmd.AddCommand(executionsCmd)
}

// ─── get ────────────────────────────────────────────────

var getExecutionCmd = &cobra.Command{
	Use:   "get <id>",
	Short: "Get execution details",
	Args:  cobra.ExactArgs(1),
	RunE:  runGetExecution,
}

func init() {
	executionsCmd.AddCommand(getExecutionCmd)
}

func runGetExecution(cmd *cobra.Command, args []string) error {
	c := mustClient()
	resp, err := c.GetExecutionWithResponse(cmd.Context(), args[0])
	if err != nil {
		return err
	}
	return printAPIResponse(resp.StatusCode(), resp.Body)
}

// ─── ai-requests ────────────────────────────────────────────────

var getExecutionAIRequestsCmd = &cobra.Command{
	Use:   "ai-requests <id>",
	Short: "Get AI requests for an execution",
	Args:  cobra.ExactArgs(1),
	RunE:  runGetExecutionAIRequests,
}

var (
	getExecutionAIRequestsCmdLimit  int
	getExecutionAIRequestsCmdOffset int
)

func init() {
	executionsCmd.AddCommand(getExecutionAIRequestsCmd)
	getExecutionAIRequestsCmd.Flags().IntVar(&getExecutionAIRequestsCmdLimit, "limit", 20, "Maximum number of AI requests to return (default 20, max 100)")
	getExecutionAIRequestsCmd.Flags().IntVar(&getExecutionAIRequestsCmdOffset, "offset", 0, "Number of AI requests to skip")
}

func runGetExecutionAIRequests(cmd *cobra.Command, args []string) error {
	c := mustClient()
	params := &client.GetExecutionAIRequestsParams{
		Limit:  &getExecutionAIRequestsCmdLimit,
		Offset: &getExecutionAIRequestsCmdOffset,
	}
	resp, err := c.GetExecutionAIRequestsWithResponse(cmd.Context(), args[0], params)
	if err != nil {
		return err
	}
	return printAPIResponse(resp.StatusCode(), resp.Body)
}

// ─── email-requests ────────────────────────────────────────────────

var getExecutionEmailRequestsCmd = &cobra.Command{
	Use:   "email-requests <id>",
	Short: "Get email requests for an execution",
	Args:  cobra.ExactArgs(1),
	RunE:  runGetExecutionEmailRequests,
}

var (
	getExecutionEmailRequestsCmdLimit  int
	getExecutionEmailRequestsCmdOffset int
)

func init() {
	executionsCmd.AddCommand(getExecutionEmailRequestsCmd)
	getExecutionEmailRequestsCmd.Flags().IntVar(&getExecutionEmailRequestsCmdLimit, "limit", 20, "Maximum number of email requests to return (default 20, max 100)")
	getExecutionEmailRequestsCmd.Flags().IntVar(&getExecutionEmailRequestsCmdOffset, "offset", 0, "Number of email requests to skip")
}

func runGetExecutionEmailRequests(cmd *cobra.Command, args []string) error {
	c := mustClient()
	params := &client.GetExecutionEmailRequestsParams{
		Limit:  &getExecutionEmailRequestsCmdLimit,
		Offset: &getExecutionEmailRequestsCmdOffset,
	}
	resp, err := c.GetExecutionEmailRequestsWithResponse(cmd.Context(), args[0], params)
	if err != nil {
		return err
	}
	return printAPIResponse(resp.StatusCode(), resp.Body)
}

// ─── logs ────────────────────────────────────────────────

var getExecutionLogsCmd = &cobra.Command{
	Use:   "logs <id>",
	Short: "Get execution logs",
	Args:  cobra.ExactArgs(1),
	RunE:  runGetExecutionLogs,
}

var (
	getExecutionLogsCmdLimit  int
	getExecutionLogsCmdOffset int
)

func init() {
	executionsCmd.AddCommand(getExecutionLogsCmd)
	getExecutionLogsCmd.Flags().IntVar(&getExecutionLogsCmdLimit, "limit", 20, "Maximum number of log entries to return (default 20, max 100)")
	getExecutionLogsCmd.Flags().IntVar(&getExecutionLogsCmdOffset, "offset", 0, "Number of log entries to skip")
}

func runGetExecutionLogs(cmd *cobra.Command, args []string) error {
	c := mustClient()
	params := &client.GetExecutionLogsParams{
		Limit:  &getExecutionLogsCmdLimit,
		Offset: &getExecutionLogsCmdOffset,
	}
	resp, err := c.GetExecutionLogsWithResponse(cmd.Context(), args[0], params)
	if err != nil {
		return err
	}
	return printAPIResponse(resp.StatusCode(), resp.Body)
}

// ─── list ────────────────────────────────────────────────

var listExecutionsCmd = &cobra.Command{
	Use:   "list <id>",
	Short: "List executions of a function",
	Args:  cobra.ExactArgs(1),
	RunE:  runListExecutions,
}

var (
	listExecutionsCmdLimit  int
	listExecutionsCmdOffset int
)

func init() {
	executionsCmd.AddCommand(listExecutionsCmd)
	listExecutionsCmd.Flags().IntVar(&listExecutionsCmdLimit, "limit", 20, "Maximum number of items to return (default 20, max 100)")
	listExecutionsCmd.Flags().IntVar(&listExecutionsCmdOffset, "offset", 0, "Number of items to skip")
}

func runListExecutions(cmd *cobra.Command, args []string) error {
	c := mustClient()
	params := &client.ListExecutionsParams{
		Limit:  &listExecutionsCmdLimit,
		Offset: &listExecutionsCmdOffset,
	}
	resp, err := c.ListExecutionsWithResponse(cmd.Context(), args[0], params)
	if err != nil {
		return err
	}
	return printAPIResponse(resp.StatusCode(), resp.Body)
}
