// Code generated by tools/gen; DO NOT EDIT.

package cmd

import (
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/dimiro1/lunar/cli/client"
	"github.com/spf13/cobra"
)

var _ = fmt.Sprintf // suppress unused import

var functionsCmd = &cobra.Command{
	Use:   "functions",
	Short: "Function management operations",
}

func init() {
	rootCmd.AddCommand(functionsCmd)
}

// ─── list ────────────────────────────────────────────────

var listFunctionsCmd = &cobra.Command{
	Use:   "list",
	Short: "List all functions",
	RunE:  runListFunctions,
}

var (
	listFunctionsCmdLimit  int
	listFunctionsCmdOffset int
)

func init() {
	functionsCmd.AddCommand(listFunctionsCmd)
	listFunctionsCmd.Flags().IntVar(&listFunctionsCmdLimit, "limit", 20, "Maximum number of items to return (default 20, max 100)")
	listFunctionsCmd.Flags().IntVar(&listFunctionsCmdOffset, "offset", 0, "Number of items to skip")
}

func runListFunctions(cmd *cobra.Command, args []string) error {
	c := mustClient()
	params := &client.ListFunctionsParams{
		Limit:  &listFunctionsCmdLimit,
		Offset: &listFunctionsCmdOffset,
	}
	resp, err := c.ListFunctionsWithResponse(cmd.Context(), params)
	if err != nil {
		return err
	}
	return printAPIResponse(resp.StatusCode(), resp.Body)
}

// ─── create ────────────────────────────────────────────────

var createFunctionCmd = &cobra.Command{
	Use:   "create",
	Short: "Create a new function",
	RunE:  runCreateFunction,
}

var (
	createFunctionCmdCode        string
	createFunctionCmdDescription string
	createFunctionCmdName        string
)

func init() {
	functionsCmd.AddCommand(createFunctionCmd)
	createFunctionCmd.Flags().StringVar(&createFunctionCmdCode, "code", "", "Lua code for the function (must be non-empty after trimming whitespace)")
	_ = createFunctionCmd.MarkFlagRequired("code")
	createFunctionCmd.Flags().StringVar(&createFunctionCmdDescription, "description", "", "Optional description")
	createFunctionCmd.Flags().StringVar(&createFunctionCmdName, "name", "", "Name for the function (must be non-empty after trimming whitespace)")
	_ = createFunctionCmd.MarkFlagRequired("name")
}

func runCreateFunction(cmd *cobra.Command, args []string) error {
	c := mustClient()
	code := createFunctionCmdCode
	if code == "-" {
		b, err := io.ReadAll(os.Stdin)
		if err != nil {
			return fmt.Errorf("reading stdin: %w", err)
		}
		code = string(b)
	}
	body := client.CreateFunctionJSONRequestBody{
		Code: code,
		Name: createFunctionCmdName,
	}
	if cmd.Flags().Changed("description") {
		v := createFunctionCmdDescription
		body.Description = &v
	}
	resp, err := c.CreateFunctionWithResponse(cmd.Context(), body)
	if err != nil {
		return err
	}
	return printAPIResponse(resp.StatusCode(), resp.Body)
}

// ─── get ────────────────────────────────────────────────

var getFunctionCmd = &cobra.Command{
	Use:   "get <id>",
	Short: "Get a specific function",
	Args:  cobra.ExactArgs(1),
	RunE:  runGetFunction,
}

func init() {
	functionsCmd.AddCommand(getFunctionCmd)
}

func runGetFunction(cmd *cobra.Command, args []string) error {
	c := mustClient()
	resp, err := c.GetFunctionWithResponse(cmd.Context(), args[0])
	if err != nil {
		return err
	}
	return printAPIResponse(resp.StatusCode(), resp.Body)
}

// ─── update ────────────────────────────────────────────────

var updateFunctionCmd = &cobra.Command{
	Use:   "update <id>",
	Short: "Update a function",
	Args:  cobra.ExactArgs(1),
	RunE:  runUpdateFunction,
}

var (
	updateFunctionCmdCode          string
	updateFunctionCmdCronSchedule  string
	updateFunctionCmdCronStatus    string
	updateFunctionCmdDescription   string
	updateFunctionCmdDisabled      bool
	updateFunctionCmdName          string
	updateFunctionCmdRetentionDays int
	updateFunctionCmdSaveResponse  bool
)

func init() {
	functionsCmd.AddCommand(updateFunctionCmd)
	updateFunctionCmd.Flags().StringVar(&updateFunctionCmdCode, "code", "", "New code (creates a new version, must be non-empty after trimming whitespace)")
	updateFunctionCmd.Flags().StringVar(&updateFunctionCmdCronSchedule, "cron-schedule", "", "Cron expression for scheduled execution (standard 5-field format: minute hour day month weekday). Examples: \\\"*/5 * * * *\\\" (every 5 minutes), \\\"0 9 * * 1-5\\\" (weekdays at 9am). Set to empty string to clear the schedule.")
	updateFunctionCmd.Flags().StringVar(&updateFunctionCmdCronStatus, "cron-status", "", "Status of the cron schedule. Set to \\\"active\\\" to enable scheduled execution.")
	updateFunctionCmd.Flags().StringVar(&updateFunctionCmdDescription, "description", "", "New description")
	updateFunctionCmd.Flags().BoolVar(&updateFunctionCmdDisabled, "disabled", false, "Set to true to disable the function (preventing execution), false to enable it")
	updateFunctionCmd.Flags().StringVar(&updateFunctionCmdName, "name", "", "New name for the function (must be non-empty after trimming whitespace)")
	updateFunctionCmd.Flags().IntVar(&updateFunctionCmdRetentionDays, "retention-days", 0, "Number of days to retain execution logs")
	updateFunctionCmd.Flags().BoolVar(&updateFunctionCmdSaveResponse, "save-response", false, "Whether to save HTTP responses with executions for debugging")
}

func runUpdateFunction(cmd *cobra.Command, args []string) error {
	c := mustClient()
	body := client.UpdateFunctionJSONRequestBody{}
	if cmd.Flags().Changed("code") {
		codeVal := updateFunctionCmdCode
		if codeVal == "-" {
			b, err := io.ReadAll(os.Stdin)
			if err != nil {
				return fmt.Errorf("reading stdin: %w", err)
			}
			codeVal = string(b)
		}
		body.Code = &codeVal
	}
	if cmd.Flags().Changed("cron-schedule") {
		v := updateFunctionCmdCronSchedule
		body.CronSchedule = &v
	}
	if cmd.Flags().Changed("cron-status") {
		v := client.UpdateFunctionRequestCronStatus(updateFunctionCmdCronStatus)
		body.CronStatus = &v
	}
	if cmd.Flags().Changed("description") {
		v := updateFunctionCmdDescription
		body.Description = &v
	}
	if cmd.Flags().Changed("disabled") {
		v := updateFunctionCmdDisabled
		body.Disabled = &v
	}
	if cmd.Flags().Changed("name") {
		v := updateFunctionCmdName
		body.Name = &v
	}
	if cmd.Flags().Changed("retention-days") {
		v := client.UpdateFunctionRequestRetentionDays(updateFunctionCmdRetentionDays)
		body.RetentionDays = &v
	}
	if cmd.Flags().Changed("save-response") {
		v := updateFunctionCmdSaveResponse
		body.SaveResponse = &v
	}
	resp, err := c.UpdateFunctionWithResponse(cmd.Context(), args[0], body)
	if err != nil {
		return err
	}
	return printAPIResponse(resp.StatusCode(), resp.Body)
}

// ─── delete ────────────────────────────────────────────────

var deleteFunctionCmd = &cobra.Command{
	Use:   "delete <id>",
	Short: "Delete a function",
	Args:  cobra.ExactArgs(1),
	RunE:  runDeleteFunction,
}

func init() {
	functionsCmd.AddCommand(deleteFunctionCmd)
}

func runDeleteFunction(cmd *cobra.Command, args []string) error {
	c := mustClient()
	resp, err := c.DeleteFunctionWithResponse(cmd.Context(), args[0])
	if err != nil {
		return err
	}
	return printAPIResponse(resp.StatusCode(), resp.Body)
}

// ─── env ────────────────────────────────────────────────

var updateEnvVarsCmd = &cobra.Command{
	Use:   "env <id>",
	Short: "Update environment variables",
	Args:  cobra.ExactArgs(1),
	RunE:  runUpdateEnvVars,
}

var (
	updateEnvVarsCmdEnvVars []string
)

func init() {
	functionsCmd.AddCommand(updateEnvVarsCmd)
	updateEnvVarsCmd.Flags().StringArrayVar(&updateEnvVarsCmdEnvVars, "env", nil, "Environment variables to set (max 100 variables). Keys must contain only letters, numbers, and underscores (max 100 chars). Values can be up to 10,000 characters.")
	_ = updateEnvVarsCmd.MarkFlagRequired("env")
}

func runUpdateEnvVars(cmd *cobra.Command, args []string) error {
	c := mustClient()
	envMap := make(map[string]string)
	for _, kv := range updateEnvVarsCmdEnvVars {
		parts := strings.SplitN(kv, "=", 2)
		if len(parts) != 2 {
			return fmt.Errorf("invalid --env format %q, expected KEY=VALUE", kv)
		}
		envMap[parts[0]] = parts[1]
	}
	body := client.UpdateEnvVarsJSONRequestBody{
		EnvVars: envMap,
	}
	resp, err := c.UpdateEnvVarsWithResponse(cmd.Context(), args[0], body)
	if err != nil {
		return err
	}
	return printAPIResponse(resp.StatusCode(), resp.Body)
}

// ─── kv ────────────────────────────────────────────────

var updateKVCmd = &cobra.Command{
	Use:   "kv <id>",
	Short: "Update key-value store",
	Args:  cobra.ExactArgs(1),
	RunE:  runUpdateKV,
}

var (
	updateKVCmdGlobal bool
	updateKVCmdKv     []string
)

func init() {
	functionsCmd.AddCommand(updateKVCmd)
	updateKVCmd.Flags().BoolVar(&updateKVCmdGlobal, "global", false, "Whether the KV pairs are global or function-scoped")
	_ = updateKVCmd.MarkFlagRequired("global")
	updateKVCmd.Flags().StringArrayVar(&updateKVCmdKv, "kv", nil, "Key-value pairs to set in the function's KV store (max 100 pairs). Keys must contain only letters, numbers, and underscores (max 100 chars). Values can be up to 10,000 characters.")
	_ = updateKVCmd.MarkFlagRequired("kv")
}

func runUpdateKV(cmd *cobra.Command, args []string) error {
	c := mustClient()
	kvMap := make(map[string]string)
	for _, kv := range updateKVCmdKv {
		parts := strings.SplitN(kv, "=", 2)
		if len(parts) != 2 {
			return fmt.Errorf("invalid --kv format %q, expected KEY=VALUE", kv)
		}
		kvMap[parts[0]] = parts[1]
	}
	body := client.UpdateKVJSONRequestBody{
		Global: updateKVCmdGlobal,
		Kv:     kvMap,
	}
	resp, err := c.UpdateKVWithResponse(cmd.Context(), args[0], body)
	if err != nil {
		return err
	}
	return printAPIResponse(resp.StatusCode(), resp.Body)
}

// ─── next-run ────────────────────────────────────────────────

var getNextRunCmd = &cobra.Command{
	Use:   "next-run <id>",
	Short: "Get next scheduled run time",
	Args:  cobra.ExactArgs(1),
	RunE:  runGetNextRun,
}

func init() {
	functionsCmd.AddCommand(getNextRunCmd)
}

func runGetNextRun(cmd *cobra.Command, args []string) error {
	c := mustClient()
	resp, err := c.GetNextRunWithResponse(cmd.Context(), args[0])
	if err != nil {
		return err
	}
	return printAPIResponse(resp.StatusCode(), resp.Body)
}
