// Code generated by tools/gen; DO NOT EDIT.

package cmd

import (
	"fmt"

	"github.com/spf13/cobra"
)

var _ = fmt.Sprintf // suppress unused import

var tokensCmd = &cobra.Command{
	Use:   "tokens",
	Short: "API token management for connected clients",
}

func init() {
	rootCmd.AddCommand(tokensCmd)
}

// ─── list ────────────────────────────────────────────────

var listTokensCmd = &cobra.Command{
	Use:   "list",
	Short: "List all API tokens",
	RunE:  runListTokens,
}

func init() {
	tokensCmd.AddCommand(listTokensCmd)
}

func runListTokens(cmd *cobra.Command, args []string) error {
	c := mustClient()
	resp, err := c.ListTokensWithResponse(cmd.Context())
	if err != nil {
		return err
	}
	return printAPIResponse(resp.StatusCode(), resp.Body)
}

// ─── revoke ────────────────────────────────────────────────

var revokeTokenCmd = &cobra.Command{
	Use:   "revoke <id>",
	Short: "Revoke an API token",
	Args:  cobra.ExactArgs(1),
	RunE:  runRevokeToken,
}

func init() {
	tokensCmd.AddCommand(revokeTokenCmd)
}

func runRevokeToken(cmd *cobra.Command, args []string) error {
	c := mustClient()
	resp, err := c.RevokeTokenWithResponse(cmd.Context(), args[0])
	if err != nil {
		return err
	}
	return printAPIResponse(resp.StatusCode(), resp.Body)
}
