// Code generated by tools/gen; DO NOT EDIT.

package cmd

import (
	"fmt"
	"strconv"

	"github.com/dimiro1/lunar/lunar-cli/client"
	"github.com/spf13/cobra"
)

var _ = fmt.Sprintf // suppress unused import

var versionsCmd = &cobra.Command{
	Use:   "versions",
	Short: "Function version management",
}

func init() {
	rootCmd.AddCommand(versionsCmd)
}

// ─── diff ────────────────────────────────────────────────

var getVersionDiffCmd = &cobra.Command{
	Use:   "diff <id> <v1> <v2>",
	Short: "Get diff between two versions",
	Args:  cobra.ExactArgs(3),
	RunE:  runGetVersionDiff,
}

func init() {
	versionsCmd.AddCommand(getVersionDiffCmd)
}

func runGetVersionDiff(cmd *cobra.Command, args []string) error {
	c := mustClient()
	v1, err := strconv.Atoi(args[1])
	if err != nil {
		return fmt.Errorf("invalid v1: %w", err)
	}
	v2, err := strconv.Atoi(args[2])
	if err != nil {
		return fmt.Errorf("invalid v2: %w", err)
	}
	resp, err := c.GetVersionDiffWithResponse(cmd.Context(), args[0], v1, v2)
	if err != nil {
		return err
	}
	return printAPIResponse(resp.StatusCode(), resp.Body)
}

// ─── list ────────────────────────────────────────────────

var listVersionsCmd = &cobra.Command{
	Use:   "list <id>",
	Short: "List all versions of a function",
	Args:  cobra.ExactArgs(1),
	RunE:  runListVersions,
}

var (
	listVersionsCmdLimit  int
	listVersionsCmdOffset int
)

func init() {
	versionsCmd.AddCommand(listVersionsCmd)
	listVersionsCmd.Flags().IntVar(&listVersionsCmdLimit, "limit", 20, "Maximum number of items to return (default 20, max 100)")
	listVersionsCmd.Flags().IntVar(&listVersionsCmdOffset, "offset", 0, "Number of items to skip")
}

func runListVersions(cmd *cobra.Command, args []string) error {
	c := mustClient()
	params := &client.ListVersionsParams{
		Limit:  &listVersionsCmdLimit,
		Offset: &listVersionsCmdOffset,
	}
	resp, err := c.ListVersionsWithResponse(cmd.Context(), args[0], params)
	if err != nil {
		return err
	}
	return printAPIResponse(resp.StatusCode(), resp.Body)
}

// ─── delete ────────────────────────────────────────────────

var deleteVersionCmd = &cobra.Command{
	Use:   "delete <id> <version-id>",
	Short: "Delete a version",
	Args:  cobra.ExactArgs(2),
	RunE:  runDeleteVersion,
}

func init() {
	versionsCmd.AddCommand(deleteVersionCmd)
}

func runDeleteVersion(cmd *cobra.Command, args []string) error {
	c := mustClient()
	resp, err := c.DeleteVersionWithResponse(cmd.Context(), args[0], args[1])
	if err != nil {
		return err
	}
	return printAPIResponse(resp.StatusCode(), resp.Body)
}

// ─── activate ────────────────────────────────────────────────

var activateVersionCmd = &cobra.Command{
	Use:   "activate <id> <version-id>",
	Short: "Activate a version",
	Args:  cobra.ExactArgs(2),
	RunE:  runActivateVersion,
}

func init() {
	versionsCmd.AddCommand(activateVersionCmd)
}

func runActivateVersion(cmd *cobra.Command, args []string) error {
	c := mustClient()
	resp, err := c.ActivateVersionWithResponse(cmd.Context(), args[0], args[1])
	if err != nil {
		return err
	}
	return printAPIResponse(resp.StatusCode(), resp.Body)
}

// ─── get ────────────────────────────────────────────────

var getVersionCmd = &cobra.Command{
	Use:   "get <id> <version>",
	Short: "Get a specific version",
	Args:  cobra.ExactArgs(2),
	RunE:  runGetVersion,
}

func init() {
	versionsCmd.AddCommand(getVersionCmd)
}

func runGetVersion(cmd *cobra.Command, args []string) error {
	c := mustClient()
	version, err := strconv.Atoi(args[1])
	if err != nil {
		return fmt.Errorf("invalid version: %w", err)
	}
	resp, err := c.GetVersionWithResponse(cmd.Context(), args[0], version)
	if err != nil {
		return err
	}
	return printAPIResponse(resp.StatusCode(), resp.Body)
}
